# Generated by Django 5.0.3 on 2024-04-02 22:06

import tests_demos.web.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fantasy', 'Fantasy'), ('horror', 'Horror'), ('science_fiction', 'Science Fiction'), ('action', 'Action'), ('comedy', 'Comedy'), ('romance', 'Romance'), ('adventure', 'Adventure'), ('thriller', 'Thriller')], default='fantasy', max_length=15),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, validators=[tests_demos.web.validators.validate_book_title]),
        ),
    ]
